package com.example.drools.rules

import com.example.drools.entity.Home

rule "LowRiskHome2"
    when
        home : Home( fireAlarmInstalled == true, numberOfFloors < 3, sprinklerInstalled == true )
    then
        System.out.println("Hoş geldiniz22 !");
        home.setPolicyPrice(113231 + home.getPolicyPrice());
end

rule "MediumRiskHome2"
    when
        home : Home( fireAlarmInstalled == true, numberOfFloors > 2, numberOfFloors < 5, sprinklerInstalled == true )
    then
        home.setPolicyPrice(22);
end

rule "HighRiskHome2"
    when
        home : Home( fireAlarmInstalled == false, numberOfFloors > 4, sprinklerInstalled == false )
    then
        home.setPolicyPrice(33);
end